plugins:
  - serverless-offline
  - serverless-dotenv-plugin

service: coinbase-listing
useDotenv: true
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    DATA_TABLE: ${self:provider.stage}-data-table
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DATA_TABLE}'

functions:
  main:
    environment:
      API_KEY: ${env:API_KEY}
      API_SECRET: ${env:API_SECRET}
    handler: src/coinbaseListing.main
    events:
      - httpApi:
          path: /api/checkListing
          method: GET
      - schedule: rate(2 minutes)

resources:
  Resources:
    data:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DATA_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 50
          WriteCapacityUnits: 50
