export const testTitles = [
  '$COIN — it’s only the beginning',
  '1inch (1INCH), Enjin Coin (ENJ), NKN (NKN) and Origin Token (OGN) are now available on Coinbase',
  'Coinbase releases investor education resources',
  'An update on improving our customer experience',
  'Polygon (MATIC), SKALE (SKL) and SushiSwap (SUSHI) are launching on Coinbase Pro',
  'Coinbase offers corporations a trusted solution for adding crypto to their corporate treasury',
  'Our Commitment to Our Customers',
  'Hedge funds continue to look to Coinbase for innovative portfolio solutions',
  'USDC v2: Upgrading a multi-billion dollar ERC-20 token',
  'Discover all the ways you can earn crypto in one place',
  '1inch (1INCH), Enjin Coin (ENJ), NKN (NKN) and Origin Token (OGN) are launching on Coinbase Pro',
  'Coinbase Announces Effectiveness of Registration Statement and Anticipated Listing Date of its…',
  'Coinbase hires Brett Redfearn as VP, Capital Markets',
  'Ankr (ANKR), Curve DAO Token (CRV) and Storj (STORJ) are now available on Coinbase',
  'Coinbase is now hiring in India',
  'Coinbase Institutional selected by Meitu for landmark treasury allocation into Ethereum and Bitcoin',
  'Ankr (ANKR) Curve DAO Token (CRV) and Storj (STORJ) are launching on Coinbase Pro',
  'Cardano (ADA) is now available on Coinbase',
  'Cardano (ADA) is launching on Coinbase Pro',
  'Polygon (MATIC), SKALE (SKL) and SushiSwap (SUSHI) are now available on Coinbase',
  'Coinbase announces filing of registration statement for proposed public direct listing of its…',
  'Coinbase is a decentralized company, with no headquarters',
  'Strengthening our commitment to trust through compliance: Melissa Strait joins Coinbase as Chief…',
  'Coinbase is committed to helping our customers during tax season',
  'Join the waitlist for Ethereum 2.0 staking rewards on Coinbase',
  'How we build payments systems at Coinbase',
  'Incident Post Mortem: January 29, 2021',
  'Around the Block #11: A snapshot of DeFi and two sides of the crypto regulatory spectrum',
  'Coinbase announces proposed direct listing',
  'Coinbase requests rulemaking pause from FinCEN following Biden White House guidance to agencies',
  'How Coinbase ran its first 100+ person online “offsite”',
  'Coinbase to acquire leading blockchain infrastructure platform, Bison Trails',
  'Committing to better customer service during this time of heightened interest in the cryptoeconomy',
  'Introducing Coinbase Asset Hub, our open invitation to asset issuers',
  'Addressing recent customer experience issues for some UK and EU users',
  'Incident Post Mortem: January 6–7, 2021',
  'Payment services in Bazel monorepo',
  'Hedge funds continue to look to Coinbase for innovative portfolio solutions',
  'USDC v2: Upgrading a multi-billion dollar ERC-20 token',
  'Make your voice heard — Share your thoughts on the new proposed crypto rules directly with the U.S. Department of Treasury',
  'Coinbase is committed to fair and equitable compensation for every employee',
  'Coinbase will suspend trading in XRP on January 19',
  'Security PSA: Ledger Phishing Attacks',
  'Announcing our first Bitcoin Core developer grants',
  'Coinbase is now hiring in Canada',
  'Coinbase’s response to recent proposed rulemaking from the U.S. Treasury and FinCEN',
  'Announcing the Rosetta Grants Program',
  'The Graph (GRT) is now available on Coinbase',
  'Coinbase announces confidential submission of draft registration statement',
  'The Graph (GRT) is launching on Coinbase Pro',
  'A message from Coinbase about crypto market rallies',
  'Kelly Kramer, former CFO of Cisco, joins Coinbase Board',
  'Grow your crypto knowledge with Coinbase',
  'Aave (AAVE), Bancor (BNT) and Synthetix (SNX) are now available on Coinbase',
  'Aave (AAVE), Bancor (BNT) and Synthetix (SNX) are launching on Coinbase Pro',
  'The art of a seamless migration of Coinbase’s internal ledger',
  'Around the Block #10: “ETH killers” and new chains',
  'Filecoin (FIL) is now available on Coinbase',
  'Filecoin (FIL) is launching on Coinbase Pro',
  'Coinbase to support Flare Network’s Spark Airdrop',
  'Empowering customers, whilst ensuring their safety',
  'Building state-of-the-art machine learning technology with efficient execution for the crypto economy',
  'Coinbase Pro to support additional order books',
  'Coinbase is helping corporate companies diversify with crypto',
  'NuCypher (NU) is now available on Coinbase',
  'Coinbase December 2020 Market Maker Program',
  'Ethereum 2.0 staking rewards are coming soon to Coinbase',
  'NuCypher (NU) is launching on Coinbase Pro',
  'An upcoming story about Coinbase',
  'Coinbase Pro disables margin trading',
  'Optimizing React Native',
  'Incident Postmortem: November 16th, 2020',
  'Civic (CVC), Decentraland (MANA), and district0x (DNT), are now available on Coinbase',
  'Fostering Trust Through Coinbase’s Growing Legal & Compliance Team',
  'Coinbase Card launches in the US',
  'Wrapped Bitcoin (WBTC) is now available on Coinbase',
  'Coinbase Custody explores support for new digital assets',
  'Transparency at Coinbase',
  'Wrapped Bitcoin (WBTC) is launching on Coinbase Pro',
  'Coinbase will sponsor two Bitcoin Core developers with first Crypto Community Fund grants',
  'Coinbase Custody now supports Filecoin ($FIL)',
];
